spring.application.name=orderms

spring.mongodb.authentication-database=admin
spring.data.mongodb.auto-index-creation=true
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring..mongodb.database=orderms
spring..mongodb.username=admin
spring..mongodb.password=adm123
